apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2019-07-24T19:55:11Z"
    generation: 2
    labels:
      name: aplicacao-pod
    name: aplicacao-deployment
    namespace: default
    resourceVersion: "186766"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/aplicacao-deployment
    uid: 0bf07b7c-473b-4f84-8775-46e751f6e70a
  spec:
    progressDeadlineSeconds: 600
    replicas: 6
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        name: aplicacao-pod
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: aplicacao-pod
      spec:
        containers:
        - image: rafanercessian/aplicacao-loja:v1
          imagePullPolicy: IfNotPresent
          name: container-aplicacao-loja
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 3
    conditions:
    - lastTransitionTime: "2019-07-24T19:55:11Z"
      lastUpdateTime: "2019-07-24T19:55:40Z"
      message: ReplicaSet "aplicacao-deployment-7846d8dfdb" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2019-10-02T19:23:10Z"
      lastUpdateTime: "2019-10-02T19:23:10Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 2
    readyReplicas: 3
    replicas: 6
    updatedReplicas: 3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
